### ISSUE TITLE
Translate “Chapter Four: Accessors, Attributes, Class Variables”

### ISSUE THREAD

**Issue by denysdovhan** [sergogovich/thelittlebookofruby#6]
**File:** `04-Accessors-Attributes-Class-Variables.md`
**Branch:** `04-accessors-attributes-class-variables`

**Chapter Four**
- [x] Accessor Methods
- [x] Attribute Readers and Writers
- [x] Attributes Create Variables
- [x] Calling Methods of a Superclass
- [x] Class Variables

**Comment by ghost** [comment]
Я починаю перекладати цей розділ.

**Comment by denysdovhan** [comment]
Done.
