### ISSUE TITLE
Translate “Chapter Five: Arrays”

### ISSUE THREAD

**Issue by denysdovhan** [sergogovich/thelittlebookofruby#7]
**File:** `05-Arrays.md`
**Branch:** `05-arrays`

**Chapter Five**
- [x] Using Arrays
- [x] Creating Arrays
- [x] Multi-Dimensional Arrays
- [x] Iterating Over Arrays
- [x] Indexing Into Arrays

**Comment by ghost** [comment]
Привіт, я хотів би взяти участь у перекладі та спробувати свої сили.
П. с. Приємно здивований, що натрапив на вас ) знаю вас по Codeguida )

**Comment by ghost** [comment]
@harusan Привіт, зв'яжися зі мною, будь ласка)

**Comment by denysdovhan** [comment]
@harusan не забудь прочитати [`CONTRIBUTING.md`](https://github.com/LambdaBooks/thelittlebookofruby/blob/master/.github/CONTRIBUTING.md) — там описано все, що необхідно для роботи.

**Comment by denysdovhan** [comment]
Done.
